### PR TITLE
Added Pushover support

### PR DESCRIPTION
**Pull request by rtgoodwin**
Opening this PR since it should be good to go. I know master has moved up quite a bit, with changes to the r/o rootfs etc. I'm seeing the same issue as #22, where the file isn't being mounted, or gets mounted and then disappears and won't remount. Maybe you've fixed it since I pulled master earlier.

Anyway, here are the changes:

- Added TESLAUSB_REPO and TESLAUSB_BRANCH vars into setup-teslausb for easier development (testing off other branches, etc. 
- Removed and gitignore DS_Store files (Mac thing...)
- Instructions for Pushover in Readme
- Setup script does conditional Pushover setup based on env vars
- Added base Pushover script for now, which will conditionally get downloaded and run if credentials have been created. 
(Future plan to expand it to a debug mode so someone can get pushes for "Connected to wifi", "Mounted share", etc. Again, useful if sitting in car!)

Followed your bash, file naming, execution as I saw them. LMK if changes/improvements recommended. I'm honestly not sure why I needed two different bash `tests` for the env vars in the check function.

### CODE REVIEW

**Comment by rtgoodwin** [comment]
Woo, master did progress A LOT! This should merge pretty cleanly though I think. I had my checks up top to determine whether to grab the extra script for sending the push. (To keep the `wget`s nicely grouped together.) That conditional could be jettisoned and just pull the script regardless; it won't be called unless the archive media loop finds `~/.teslaCamPushoverCredentials` when running.

**Comment by cimryan** [comment]
Looks good! Can you merge master into this branch so it'll merge cleanly?

**Comment by rtgoodwin** [comment]
I'm honestly not sure how to do that properly with Git, but I'll give it a go. (I believe it's a fetch and merge and then some magic about fast forwarding or not. To the Googles!) 

Worst case, I'll port my changes back to master and PR to you with that.

**Comment by firedfly** [comment]
I like the REPO and BRANCH variables.  Makes it much easier to test changes.

**Comment by rtgoodwin** [comment]
(And reported in other issue, block error is fixed with new instructions, which I'll also try to automate with the pre-boot update script at some point along with the wifi. So error was def unrelated to this branch.)

**Pull request merged**
