### PR TITLE
Clean shutdown

### PR DESCRIPTION
**Pull request by Poncherelly**
Retracted

### CODE REVIEW

**Comment by marcone** [comment]
Please close this pull request, as it is requesting that the entire "marcone" fork is merged in to this one, which is inappropriate.
(also, it sounds like you wanted to file a feature request. You should do that under the "issues" tab, not the "pull requests" tab)

**Comment by marcone** [comment]
@Poncherelly Please close this pull request, as it is requesting that the entire "marcone" fork be merged in to this one, which is inappropriate.

**Comment by Poncherelly** [comment]
Sorry about that. Still new to Github.

I'm not sure how to delete my ask, I've however retracted my comments.



Richard

Purchasing a TESLA?  Please use My Referral Code<https://ts.la/richard48613> for free supercharging.

**Comment by marcone** [comment]
@Poncherelly you should see a "close pull request" button at the bottom. That's the one you want to click :)

**Comment by Poncherelly** [comment]
I'm feeling really stupid but I don't see it.


Richard

Purchasing a TESLA?  Please use My Referral Code<https://ts.la/richard48613> for free supercharging.

**Comment by Poncherelly** [comment]
Found it :(  again, sorry.


Richard

Purchasing a TESLA?  Please use My Referral Code<https://ts.la/richard48613> for free supercharging.

**Pull request closed without merging**
