### PR TITLE
U/rtanaka/organizing

### PR DESCRIPTION
**Pull request by cimryan**

### CODE REVIEW

**Comment by cimryan** [comment]
There are a few things I'd like to see changed, here. I have family in town so I'm not sure how much I'll be able to do myself, this week.

I welcome debate on these points.

I'd prefer that we verify what we can before we make any changes to the Pi. Using the /root/.teslaCamCredentials file seems like it might contradict this principle.

I prefer for "check" functions to be Pure functions.

We have global variables, script-local variables, and function-local variables. Using "export" to make a function-local variable script-local worries me because I think it also makes the variable global. Is this impression mistaken?

**Comment by cimryan** [comment]
> what do you think of splitting the setup from the configuring of the archive? the current setup script can partition and get the base files. and then follow it up with a configure script that will write out the archive config and download the respective scripts to support it.

Seems reasonable.

**Comment by rtanaka** [comment]
just as an fyi - `campercent` is now the only essential setting that is required at the time of running `setup-teslausb`.  the rest of the environment variables need to be set prior to running configure and it will write the configs and pull the latest scripts.

**Comment by rtgoodwin** [comment]
> hey there. i split this up because as you know, setting up the partitions is more of a one time thing and failing to mount your archive currently breaks the whole process. the split allows you to run configure multiple times to get (and eventually change/update) your archive server without a full reinstall.

> from a functional perspective if you add configure immediately after setup-teslausb it will result in the same outcome. i haven't added your headless specific logging items into the new configure script. along those lines i believe we should split out some common functions (your headless logging, led blinking, get_script, check_variable) into a separate lib so both scripts can leverage them.

You can look at the pi-gen sources now merged here and make suggestions too; I'm quite open, and we can play there without disrupting anyone. I don't want to cut a new public with the different configure line w/o the setup logging and new structure on the main branch, ideally; I will go ahead and make one with just the configure line added for us to test with. BTW is there a chat going on anywhere? A Discord or Slack or Gitter would be dandy at this point. :) If not, I can create one. I'll go cut that image and check back here with the url.

**Comment by rtgoodwin** [comment]
Here you go! [Slack invite link](https://join.slack.com/t/smartusbdrivefortesla/shared_invite/enQtNDY4NDIzMTQ0NjA4LTdlYjFkOGE0Y2NkNjYyZTBiZTNmZTY4OGNhODMwZjg4NGNkZWU3MGY2ZDNhODIzZTAxODhhNzEzNDQ2OTFhMTI)

**Comment by cimryan** [comment]
It seems reasonable to have three entry-points for manual setup on the Pi:
1. A "partition" script
2. A "configure archiving" script
3. A user-friendly wrapper for the other two

Verification of the reachability of the archive was added in response to actual reported failures, and those failures were particularly mystifying because they happened when there was no opportunity to present the user with the problem. So, defaulting to performing validation of the configuration of the archive by actually attempting to connect to it seems warranted. Having said that, supporting scenarios in which the Pi is being set up away from the network by someone confident in their ability to properly escape passwords seems reasonable. I imagine a "SKIP_ARCHIVE_VERIFICATION" setting or some such could be one way of supporting this scenario.

I'm not convinced that we'll be able to support reconfiguration of the archive system, in general, but I'm not confident that we won't, either. You make good points about the tedium of re-applying customization, even if I suspect that most people won't bother to even change the password. Having said that, I think of the difference between the "run" and "setup" directories in the repo as being that the "run" stuff is meant to be left on the device whereas the "setup" could generally be cleaned off the device after it was configured. If you want to switch to a different archive system, it's likely that you'll need to be doing some downloading. (E.g. maybe you're switching to Google's new brain-implant file share system, and we didn't support that when you originally set up your Pi.)

Putting all the functions for a single archive system into a single file which could be sourced is an interesting idea. I think there could be some benefit that I'm not thinking of, at the moment. On the other hand, defining the "interface" with a list of file names is actually somewhat clarifying: It's easy to compare the directories and see if anything is missing. (Particularly if we were to adopt a convention of putting ancillary scripts into child directories.) File content is a little noisier to compare.

I'll defer to your judgement on the question of the argument parsing and the debug output. I'm not sure we need different levels of output, but I think reasonable people can disagree on that point.

I've attempted to make a couple of concrete proposals (with some variable degree of precision). I don't mean to ask you or anyone else to implement those proposals; I'll get to them when I can. But if you or anyone else wants to tackle those changes, I welcome you to beat me to it. I expect that I'll have time this weekend.

Please let me know if you think that there are still points to debate; in my mind we've identified a set of changes that will satisfy the goals we've each expressed.

**Comment by rtgoodwin** [comment]
My thoughts, in no particular order. (And @cimryan (and others)  [feel free to join the Slack channel](https://join.slack.com/t/smartusbdrivefortesla/shared_invite/enQtNDY4NDIzMTQ0NjA4LTdlYjFkOGE0Y2NkNjYyZTBiZTNmZTY4OGNhODMwZjg4NGNkZWU3MGY2ZDNhODIzZTAxODhhNzEzNDQ2OTFhMTI)!) 
* You shouldn’t fail base setup unless something’s awfully wrong. Defining "base" as "if you defined nothing or something went wrong you still end up with a usable USB drive and scripts to continue if desired".
* The partition layout should be pretty standardized (a cam store, tmpfs, mutable, and optionally music). This seems like something that can be made to happen regardless of any configuration provided (with CAMPERCENT=100)
* I think calling a post-base configure should be doable based on config being provided or not. It also means a very stable first stage base setup (as above) can be put in the image, which I like. The standard mutable partition would provide scratch space for downloading further scripts based on either manual or automatic input (via config). 
* I think wifi setup has to be pretty standardized too; in all but the rarest cases I would say that wifi will be required. It could be broken out from the main config file, but at a certain point it feels like you're just mimicking the `wpa_supplicant.conf` functionality. That said, for many people, editing (or generating) a single file is quite appealing, and env vars are pretty friendly. So a well baked wifi-enable script (taking config file or prompting) could/should be built into the base image. 
* Anything baked into the image would also have the option of using Python or other, so they could be less brittle than `bash` (not that I'm knocking bash...I just stink at it. :) )

I have a Jenkins server set up for automatic base image builds now. I'll add you to [my pi-gen repo](https://github.com/rtgoodwin/pi-gen) as a collaborator @cimryan. Any branch created as `feature/something` should get built automatically and [available for download](https://docean.hotsawce.com/teslausb_images/). (Note to anyone reading this, these are not necessarily production ready since it's designed for development.)

**Comment by rtanaka** [comment]
> It seems reasonable to have three entry-points for manual setup on the Pi:
> 
> 1. A "partition" script
> 2. A "configure archiving" script
> 3. A user-friendly wrapper for the other two

100% on agree with this approach

> 
> Verification of the reachability of the archive was added in response to actual reported failures, and those failures were particularly mystifying because they happened when there was no opportunity to present the user with the problem. So, defaulting to performing validation of the configuration of the archive by actually attempting to connect to it seems warranted. Having said that, supporting scenarios in which the Pi is being set up away from the network by someone confident in their ability to properly escape passwords seems reasonable. I imagine a "SKIP_ARCHIVE_VERIFICATION" setting or some such could be one way of supporting this scenario.

I have no issues with the verifying the reachability of the archive servers. The main issue was it was coupled to the "partition" script. This is solved with #81 now.

> I'm not convinced that we'll be able to support reconfiguration of the archive system, in general, but I'm not confident that we won't, either. You make good points about the tedium of re-applying customization, even if I suspect that most people won't bother to even change the password. Having said that, I think of the difference between the "run" and "setup" directories in the repo as being that the "run" stuff is meant to be left on the device whereas the "setup" could generally be cleaned off the device after it was configured. If you want to switch to a different archive system, it's likely that you'll need to be doing some downloading. (E.g. maybe you're switching to Google's new brain-implant file share system, and we didn't support that when you originally set up your Pi.)

I understand your point (and sign me up for the brain-implant file share). I do want to point out we can switch between CIFs and sftp/rscync with no downloads.

> Putting all the functions for a single archive system into a single file which could be sourced is an interesting idea. I think there could be some benefit that I'm not thinking of, at the moment. On the other hand, defining the "interface" with a list of file names is actually somewhat clarifying: It's easy to compare the directories and see if anything is missing. (Particularly if we were to adopt a convention of putting ancillary scripts into child directories.) File content is a little noisier to compare.

I can argue against either, but in the spirit of closing out #81. Let's leave this structure alone for the time being.

> I'll defer to your judgement on the question of the argument parsing and the debug output. I'm not sure we need different levels of output, but I think reasonable people can disagree on that point.

After hearing your input as well as after discussion with @rtgoodwin i believe it's best to keep the configure script simple and maintain its ability to run as a headless setup. Let's remove the bells and whistles until we actually need it.

> I've attempted to make a couple of concrete proposals (with some variable degree of precision). I don't mean to ask you or anyone else to implement those proposals; I'll get to them when I can. But if you or anyone else wants to tackle those changes, I welcome you to beat me to it. I expect that I'll have time this weekend.

I'll have some time off and on too we can also coordinate over [slack](https://join.slack.com/t/smartusbdrivefortesla/shared_invite/enQtNDY4NDIzMTQ0NjA4LTdlYjFkOGE0Y2NkNjYyZTBiZTNmZTY4OGNhODMwZjg4NGNkZWU3MGY2ZDNhODIzZTAxODhhNzEzNDQ2OTFhMTI) (this plug is for you @rtgoodwin)

> Please let me know if you think that there are still points to debate; in my mind we've identified a set of changes that will satisfy the goals we've each expressed.

The only open item that I believe is to figure out what we want to do about the `archive_module` concept. I'd like to keep it for now.

Thanks for responding - I know you said you had family in town.

**Comment by cimryan** [comment]
I couldn't figure out a good name for a script did "everything else except configure the archive". So, I left all the setup in setup-teslausb and just made that the user-friendly wrapper. I added an environment variable test for CONFIGURE_ARCHIVING so that that advanced users could skip the configuration of the archive during the setup process.

**Pull request merged**
