### PR TITLE
Support firmware 2019.5.x path names

### PR DESCRIPTION
**Pull request by marcone**
Firmware 2019.5.x changed the naming pattern of the recording files,
as well as their location. Archive both old and new files.

### CODE REVIEW

**Comment by marcone** [comment]
(I only tested the cifs backup script)

**Comment by ghost** [comment]
I pulled this down and also tested cifs.  Looks good to me.  Model 3 on 2019.5.15.

**Comment by LBegnaud** [comment]
It seems like the `mv` command fails to move the remaining items in the folder if the transfer is interrupted. This is in the case of `SavedClips` folder existing.

There's some suggestions here on how to resolve: 
https://unix.stackexchange.com/questions/9899/how-to-overwrite-target-files-with-mv

not really sure which is the best method

**Comment by marcone** [comment]
I reworked the CIFS archive-clips script so it moves the files one at a time, which allows interrupting and resuming the backup.

**Comment by AngusThermo-Pyle** [comment]
Rsync also fails if you don't have both paths present, works fine if you create the dummy directory or remove the path you don't have from the rsync command.

**Pull request closed without merging**
